- name: "clone app: {{ app.name }}"
  git:
    repo: 'https://github.com/{{ app.repo }}'
    dest: "{{ aiidalab_apps_folder }}/{{ app.name }}"
    force: true
    version: "{{ app.version }}"
    accept_hostkey: true
    recursive: false

- name: install server-side dependencies
  pip:
    name: "{{ app.requirements_server }}"
    virtualenv: "{{ aiidalab_server_venv }}"

- name: install client-side dependencies
  pip:
    name: "{{ app.requirements_client }}"
    virtualenv: "{{ aiidalab_client_venv }}"

# - name: install jupyter extensions
#   shell: "{{ aiidalab_venv }}/bin/jupyter nbextension install --sys-prefix --py {{ item }}"
#   args:
#     creates: "{{ aiidalab_venv }}/share/jupyter/nbextensions/{{ item }}/extension.js"
#   with_items:
#   - fileupload
