- name: create ${HOME}/Desktop
  file:
    path: "${HOME}/Desktop"
    state: directory

- name: Copy AiiDa Lab logo
  become: true
  become_user: "{{ root_user }}"
  copy:
    src: aiidalab_gears_square_256.png
    dest: /usr/share/icons/

- name: Create desktop shortcut to Jupyter Lab launcher
  template:
    src: aiidalab.desktop
    dest: "${HOME}/Desktop"
    mode: "0755"
