- name: Install apt requirements
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
    - git
    - povray # TODO this should probably be moved to a `requirements_apt` section on an app

- name: Create required folders
  include_tasks: folders.yml

- name: "Install appmode in {{ aiidalab_jupyter_venv }}"
  pip:
    virtualenv: "{{ aiidalab_jupyter_venv }}"
    name:
    - appmode~=0.8.0

# tip: if this is not called then the launcher will hang on the loading (cogs) screen
- name: Enable app mode nbextension
  shell: "{{ aiidalab_jupyter_venv }}/bin/jupyter nbextension enable --sys-prefix --py appmode"
  changed_when: false

# note this originates from "{{ aiidalab_jupyter_venv }}/lib/python{{ aiida_python_version | default('3.7') }}/site-packages/appmode/static/gears.svg"
# but replacing it there, after pip install, was too late
# the other approach would be to clone the appmode repo, replace the file, then install
- name: "Replace appmode gears.svg"
  copy:
    src: aiidalab_gears.svg
    dest: "{{ aiidalab_jupyter_venv }}/share/jupyter/nbextensions/appmode/gears.svg"

- name: Enable app mode serverextension
  shell: "{{ aiidalab_jupyter_venv }}/bin/jupyter serverextension enable --sys-prefix --py appmode"
  changed_when: false

- name: Install AiiDA Lab apps
  include_tasks: apps.yml

- name: Pre-build Jupyter Lab Assets  # otherwise the user will be asked to build them
  # minimize false improves the CPU and memory usage
  shell: "{{ aiidalab_jupyter_venv }}/bin/jupyter lab build --minimize=False"
  changed_when: false

- name: Clean Jupyter Lab build staging  # see https://jupyterlab.readthedocs.io/en/latest/user/directories.html#jupyterlab-build-process
  shell: "{{ aiidalab_jupyter_venv }}/bin/jupyter lab clean"
  changed_when: false

- name: Add AiiDA Lab launcher script
  become: true
  become_user: "{{ root_user }}"
  template:
    src: aiidalab_launch.sh
    dest: "/usr/local/bin/aiida-aiidalab"
    mode: "0755"

- name: Add AiiDA Lab desktop shortcut
  when: vm_headless is defined and not vm_headless
  include_tasks: desktop.yml
