- import_tasks: prerequisites.yml
  tags: [aiidalab_prerequisites]

- import_tasks: setup.yml
  tags: [aiidalab_setup]

- include_tasks: apps.yml
  vars:
    app: "{{ item }}"
  loop: "{{ aiidalab_apps|flatten(levels=1) }}"
  tags: [aiidalab_apps]
