# Note: AiiDA lab has dropped python2 support for aiida 1.0
- name: Install python3 pip and git
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
     - git
     - python3-pip

- name: install virtualenv
  become: true
  become_user: "{{ root_user }}"
  pip:
    name: virtualenv
    executable: pip3

- name: "Let virtualenvwrapper use the correct python version"
  lineinfile:
    path: "${HOME}/.bashrc"
    regex: "export VIRTUALENVWRAPPER_PYTHON=.*"
    line: "export VIRTUALENVWRAPPER_PYTHON={{ ansible_python_interpreter }}"
  when: ansible_python_interpreter is defined

- name: Check whether pymatgen is already present (for idempotency)
  shell: pip show pymatgen | grep Version | cut -d ' ' -f 2
  ignore_errors: true
  changed_when: false
  register: pymatgen_version

# Need to install numpy before aiida-core because otherwise the pymatgen
# install is broken, see https://github.com/materialsproject/pymatgen/issues/1520
- name: Install numpy compliant with pymatgen
  pip:
    name:
    - numpy==1.17.5
    virtualenv: "{{ aiidalab_venv }}"
  when: pymatgen_version.stdout

- name: Install appmode on virtual env
  pip:
    name:
    - appmode==0.8.0
    virtualenv: "{{ aiidalab_venv }}"

- name: Install aiidalab
  pip:
    name: aiidalab
    version: "{{ aiidalab_version }}"
    virtualenv: "{{ aiidalab_venv }}"
    # extra_args: --no-use-pep517
  notify: reentry scan

- name: activate ipython kernel
  shell: "{{ aiidalab_venv }}/bin/python -m ipykernel install --user"
  args:
    creates: "${HOME}/.local/share/jupyter/kernels/python3/kernel.json"

- name: install jupyter extensions
  shell: "{{ aiidalab_venv }}/bin/jupyter nbextension install --sys-prefix --py {{ item }}"
  args:
    creates: "{{ aiidalab_venv }}/share/jupyter/nbextensions/{{ item }}/extension.js"
  with_items:
  - fileupload
