---
- name: Install pip
  become: true
  become_user: "{{ root_user }}"
  apt:
    name: "python-pip"

- name: install virtualenv
  become: true
  become_user: "{{ root_user }}"
  pip:
    name: virtualenv

- name: "Let virtualenvwrapper use the correct python version"
  lineinfile:
    path: "${HOME}/.bashrc"
    regex: "export VIRTUALENVWRAPPER_PYTHON=.*"
    line: "export VIRTUALENVWRAPPER_PYTHON={{ ansible_python_interpreter }}"
  when: ansible_python_interpreter is defined

# Note: This can be joined with aiidalab once a new version is released
- name: Install pip version for aiida-core 1.0.0b2
  pip:
    # name: aiidalab
    # version: "{{ aiidalab_version }}"
    name: 
      - pip==18.1
    virtualenv: "{{ aiidalab_venv }}"
    virtualenv_site_packages: true

- name: Install aiidalab python package
  pip:
    # name: aiidalab
    # version: "{{ aiidalab_version }}"
    name: 
      - git+https://github.com/aiidalab/aiidalab-metapkg@develop-py3#egg=aiidalab
    virtualenv: "{{ aiidalab_venv }}"
    # extra_args: --no-use-pep517

- name: activate ipython kernel
  shell: "{{ aiidalab_venv }}/bin/python -m ipykernel install --user"
  args:
    creates: "${HOME}/.local/share/jupyter/kernels/python2/kernel.json"

- name: install jupyter extensions
  shell: "{{ aiidalab_venv }}/bin/jupyter nbextension install --sys-prefix --py {{ item }}"
  args:
    creates: "{{ aiidalab_venv }}/share/jupyter/nbextensions/{{ item }}/extension.js"
  with_items:
    - fileupload
