---
- name: Install pip
  become: true
  become_user: "{{ root_user }}"
  apt:
    name: "python-pip"

- name: install virtualenv
  become: true
  become_user: "{{ root_user }}"
  pip:
    name: virtualenv

# Need to install numpy before aiida-core because otherwise the pymatgen
# install is broken, see https://github.com/materialsproject/pymatgen/issues/1520
- name: Install numpy & pip
  pip:
    name:
      - pip==19.0.3
      - numpy==1.16.4
    virtualenv: "{{ aiidalab_venv }}"

- name: Install aiidalab prerequisites (python2)
  pip:
    name: aiidalab
    version: "{{ aiidalab_version }}"
    virtualenv: "{{ aiidalab_venv }}"

- name: activate ipython kernel
  shell: "{{ aiidalab_venv }}/bin/python -m ipykernel install --user"
  args:
    creates: "${HOME}/.local/share/jupyter/kernels/python2/kernel.json"

- name: install jupyter extensions
  shell: "{{ aiidalab_venv }}/bin/jupyter nbextension install --sys-prefix --py {{ item }}"
  args:
    creates: "{{ aiidalab_venv }}/share/jupyter/nbextensions/{{ item }}/extension.js"
  with_items:
    - fileupload
