- name: Converge
  hosts: all
  become: true

  roles:
  - role: marvel-nccr.aiidalab
    vars:
      vm_headless: false  # test creation of desktop shortcut

  post_tasks:
  - name: "run pip check for: {{ aiidalab_aiida_venv }}"
    command: "{{ aiidalab_aiida_venv }}/bin/pip check --no-color"
    changed_when: false

  - name: "run pip check for: {{ aiidalab_jupyter_venv }}"
    command: "{{ aiidalab_jupyter_venv }}/bin/pip check --no-color"
    changed_when: false
