- name: Converge
  hosts: all
  become: true

  roles:
  - role: marvel-nccr.aiidalab

  # post_tasks:
  # - name: run pip check
  #   command: "{{ aiidalab_server_venv }}/bin/pip check --no-color"
  #   changed_when: false
