- name: Converge
  hosts: all
  become: true

  pre_tasks:
  - name: Update apt cache.
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name:
      - quantum-espresso
    when: ansible_os_family|lower == 'debian'

  tasks:
  - name: Install nodejs 12.x
    include_role:
      name: geerlingguy.nodejs
    vars:
      nodejs_version: 12.x
      nodejs_install_npm_user: root

  - name: Install aiida
    include_role:
      name: marvel-nccr.aiida
    vars:
      # aiida_venv: "${HOME}/.virtualenvs/aiida"
      # aiida_computer_cpus: 1
      aiida_plugins:
        aiida-quantumespresso:
          version: "3.2.0"
          code_prefix: qe
          codes_var: "quantum_espresso_executables"
      quantum_espresso_executables:
      - name: pw
        folder: /usr/bin"
        executable: "pw.x"
        plugin: quantumespresso.pw
      aiida_pseudopotentials:
      - name: SSSP_1.1_efficiency
        file: SSSP_efficiency_pseudos.aiida
        url: https://archive.materialscloud.org/record/file?record_id=22&file_id=ea53f742-5f57-40b9-854b-9c34dc2bdbb3&filename=SSSP_efficiency_pseudos.aiida
        home_page: https://materialscloud.org/sssp/
        description: >-
          Standard Solid State Pseudopotentials (efficiency)
          for the PBE functional
