- name: Selenium prerequisites
  hosts: all

  vars:
  - root_user: root
    # Name of virtual display in which to run browser (via xvfb).
    virtual_display: :1
    selenium_venv: "${HOME}/.virtualenvs/selenium"

  tasks:
  - name: install apt packages
    become: true
    become_user: "{{ root_user }}"
    apt:
      name:
      - firefox
      - python3
      - python3-pip
      - netcat
      - xvfb

  - name: install xvfb init.d daemon script
    become: true
    become_user: "{{ root_user }}"
    template:
      src: templates/xvfb-init.d.j2
      dest: /etc/init.d/xvfb
      mode: 0755

  - name: start xvfb service
    become: true
    become_user: "{{ root_user }}"
    service:
      name: xvfb
      state: reloaded

  - name: install virtualenv
    become: true
    become_user: "{{ root_user }}"
    pip:
      name: virtualenv
      executable: pip3

  - name: "Let virtualenvwrapper use the correct python version"
    lineinfile:
      path: "${HOME}/.bashrc"
      regex: "export VIRTUALENVWRAPPER_PYTHON=.*"
      line: "export VIRTUALENVWRAPPER_PYTHON={{ ansible_python_interpreter }}"
    when: ansible_python_interpreter is defined

  - name: Install selenium & pytest
    pip:
      name:
      - selenium==3.141.0
      - pytest==5.4.3
      - pytest-selenium==1.17.0
      virtualenv: "{{ selenium_venv }}"

  - name: Copy test files
    copy:
      src: selenium-tests
      dest: "${HOME}/tests"

  - name: Run pytest
    shell: "{{ selenium_venv }}/bin/python -m pytest ${HOME}/tests --driver Firefox"

# ENV AIIDALAB_HOST=aiidalab AIIDALAB_PORT=8888 SELENIUM_HOST=seleniumhub SELENIUM_PORT=4444

# ENV APP_NOTEBOOKS='**/[!.]*.ipynb'
